### PR TITLE
Changes to clean up and modernize arthropodegg mod.

### PR DESCRIPTION
**Pull request by ProgrammerDan**
* Pom uses export-filter now to propogate version and plugin title to plugin.yml
* travis.yml cleaned up and eclipse artifact removed
* Some basic class comments
* optimized if/else sequence of command identification
* Maybe more.

Build tested (lightly) against 1.8.7. Note custom Spigot build version to deal with conflicted version for NMS reasons (doesn't apply to this plugin).

### CODE REVIEW

**Comment by ttk2** [comment]
I will leave this for @rourke750  to review.

**Comment by ProgrammerDan** [comment]
@Rourke750 everything here should be static change, largely cleanup and pom.xml/plugin.yml  improvements like we discussed.

**Comment by rourke750** [comment]
@ProgrammerDan Yea this is perfect.

**Comment by ttk2** [comment]
no jenkins build...

**Comment by rourke750** [comment]
@ProgrammerDan Whered you get the api reference?

**Comment by ProgrammerDan** [comment]
You referring to [this](https://github.com/Civcraft/AFK-Player-GC/pull/4#issuecomment-122334788)?

**Comment by ProgrammerDan** [comment]
Oh nevermind, I see the issue. Was just following the NMS pattern, I guess it should have been CraftBukkit1.8.7 :-/  Did you go ahead and install the jar under the new name?

**Comment by rourke750** [comment]
No I just added spigot api.  I don't believe you can use craftbukkit or spigot references since that would defeat the purpose of build tools.,  It would only work locally.

**Comment by ProgrammerDan** [comment]
Look in the history, I kept the dependency the same just upped the version.

**Comment by rourke750** [comment]
We hardly ever need to rebuild this jar.  The dependency was really outdated.

**Comment by ProgrammerDan** [comment]
yeah, tried to update it correctly but I guess spigot changed their naming scheme after DMCA. 

Anyway, I edited the prior comment with a QQ for you, since we've got inconsistencies in our dependencies.

**Pull request merged**
